### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by dallinb** [cbdq-io/docker-grype#19]
Improvements should be:

- [x] Use https://github.com/cbdq-io/docker-grype/community to add:
  - [x] A contributing guide
  - [x] Issue templates
  - [x] A code of conduct
- [x] Move the release section from the PR template to the contributing guide
- [x] Add data persistence to the README for the downloaded vulnerabilities DB
- [x] Check the volumes being used in the Docker Compose example and see if they are actually necessary.
- [x] Perhaps (clear with client first) include Drone CI (K8s pipeline) example.

**Comment by dallinb** [comment]
Drone CI (Kubernetes pipeline) snippets:

```YAML
services:
  - name: docker
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
```

```yaml
steps:
  - name: Anchore Grype
    commands:
      - /usr/local/bin/docker-grype-cmd.sh
    environment:
      IMAGE_NAME: my-image:latest
    image: cbdq/docker-grype:latest
    pull: if-not-exists
    volumes:
      - name: dockersock
        path: /var/run
```
