### ISSUE TITLE
Incorrect Columns

### ISSUE THREAD

**Issue by dallinb** [cbdq-io/docker-grype#27]
**Describe the bug**
Vulnerability report headers are showing `NAME,INSTALLED,VULNERABILITY,SEVERITY` but then a sample line is `libcrypt,2.26-35.amzn2,ALAS-2021-1605,High,no` which has an extra column (allowed) which isn't being shown in the header.

**Expected behavior**
The number of columns in the output lines should match the number of columns in the header.

**Screenshots**
The output was:
```
NAME,INSTALLED,VULNERABILITY,SEVERITY
libcrypt,2.26-35.amzn2,ALAS-2021-1605,High,no
libcrypt,2.26-35.amzn2,ALAS-2021-1599,High,no
```

**Additional context**
When this was observed, the following environment variables were being provided:
- DOCKER_HOST
- IMAGE_NAME
- VULNERABILITIES_ALLOWED_LIST

**Comment by dallinb** [comment]
While fixing this, will also update the Drone CI sample in the documentation.  A recent Drone update blocked the use of shared sockets, therefore the new configuration should be:

```YAML
services:
  - name: docker
    image: docker:dind
```

```YAML
steps:
  - name: Anchore Grype
    commands:
      - /usr/local/bin/docker-grype-cmd.sh
    environment:
      DOCKER_HOST: tcp://docker:2375
      IMAGE_NAME: my-image:latest
    image: cbdq/docker-grype:latest
    pull: if-not-exists
```
